version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - .:/var/www/html
    container_name: yii2-php

  nginx:
    image: nginx:stable
    ports:
      - "8080:80"   # frontend
      - "8081:81"   # backend
    volumes:
      - .:/var/www/html
      - ./nginx-frontend.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-backend.conf:/etc/nginx/conf.d/backend.conf
    depends_on:
      - php
    container_name: yii2-nginx

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: yii2-mysql
volumes:
  mysql_data:
